language: cpp

install:
  - git clone https://chromium.googlesource.com/external/gyp

matrix:
  include:
  - os: osx
    osx_image: xcode8.3
    script:
    - ./gyp/gyp --depth ./ ./gai++/gai.gyp
    - xcodebuild
